/** Shared design tokens for student-facing pages (matches Login / Lecturer dashboard). */
export const T = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(145deg, #f7f5f0 0%, #ebe8e1 50%, #e4e0d8 100%)',
    padding: '20px 16px',
    fontFamily: "'DM Sans', 'Segoe UI', system-ui, sans-serif",
    color: '#1a1917',
    boxSizing: 'border-box',
  },
  wrap: {
    width: '100%',
    maxWidth: '420px',
  },
  header: {
    textAlign: 'center',
    marginBottom: '20px',
  },
  logo: {
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    background: '#1a1917',
    color: '#f7f5f0',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 700,
    marginBottom: '12px',
  },
  brand: {
    fontSize: '20px',
    fontWeight: 700,
    margin: '0 0 4px',
    letterSpacing: '-0.02em',
    color: '#1a1917',
  },
  tagline: {
    fontSize: '13px',
    color: '#6b6963',
    margin: 0,
    lineHeight: 1.5,
  },
  card: {
    background: '#fff',
    borderRadius: '16px',
    padding: '28px 24px',
    boxShadow: '0 16px 48px rgba(26, 25, 23, 0.08)',
    border: '1px solid #e8e6e1',
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: '0 0 4px',
    letterSpacing: '-0.02em',
  },
  cardSubtitle: {
    fontSize: '13px',
    color: '#6b6963',
    margin: '0 0 20px',
    lineHeight: 1.5,
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 600,
    color: '#4a4845',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '12px 14px',
    marginBottom: '16px',
    borderRadius: '10px',
    border: '1px solid #e8e6e1',
    fontSize: '15px',
    boxSizing: 'border-box',
    outline: 'none',
    background: '#faf9f7',
    color: '#1a1917',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
  },
  inputFocus: {
    borderColor: '#1a1917',
    boxShadow: '0 0 0 3px rgba(26, 25, 23, 0.08)',
  },
  button: (disabled) => ({
    width: '100%',
    padding: '14px',
    background: disabled ? '#a09d97' : '#1a1917',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '15px',
    fontWeight: 600,
    cursor: disabled ? 'not-allowed' : 'pointer',
    transition: 'opacity 0.15s ease, transform 0.1s ease',
  }),
  alert: (variant) => {
    const map = {
      error: { bg: '#faece7', border: '#fac4b3', color: '#9c4221' },
      success: { bg: '#ecfdf3', border: '#bbf7d0', color: '#166534' },
      info: { bg: '#f3f2ef', border: '#e8e6e1', color: '#4a4845' },
      warn: { bg: '#fffbeb', border: '#fde68a', color: '#92400e' },
    }
    const v = map[variant] || map.info
    return {
      background: v.bg,
      border: `1px solid ${v.border}`,
      color: v.color,
      padding: '10px 14px',
      borderRadius: '10px',
      fontSize: '13px',
      marginBottom: '16px',
      lineHeight: 1.5,
      display: 'flex',
      alignItems: 'flex-start',
      gap: '8px',
    }
  },
  steps: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 8px',
  },
  step: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    marginBottom: '14px',
    fontSize: '14px',
    color: '#4a4845',
    lineHeight: 1.45,
  },
  stepNum: {
    flexShrink: 0,
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    background: '#f3f2ef',
    color: '#1a1917',
    fontSize: '12px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    textAlign: 'center',
    fontSize: '12px',
    color: '#a09d97',
    marginTop: '20px',
    lineHeight: 1.5,
  },
  successIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: '#ecfdf3',
    color: '#166534',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    margin: '0 auto 16px',
  },
  errorIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: '#faece7',
    color: '#9c4221',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    margin: '0 auto 16px',
  },
}
