# Generated by Django 5.2.13 on 2026-05-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
