# Generated by Django 5.2.13 on 2026-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
